export const P24ErrorCodeMapping: Record<string, string | undefined> = {
  err00: 'Invalid script call',
  err01: 'No confirmation received from the store for authorization response',
  err02: 'No authorization response received',
  err03: 'This request has already been processed',
  err04: 'Authorization request is incomplete or incorrect',
  err05: 'Failed to read online store configuration',
  err06: 'Failed to save authorization request',
  err07: 'Another user is making the payment',
  err08: 'Uncertain connection status with the store',
  err09: 'Exceeded the allowed number of data corrections',
  err10: 'Invalid transaction amount!',
  err49: 'Transaction risk score too high',
  err51: 'Invalid page request',
  err52: 'Incorrect session feedback!',
  err53: 'Transaction error!',
  err54: 'Transaction amount mismatch!',
  err55: 'Invalid response code!',
  err56: 'Invalid card',
  err57: 'TEST flag mismatch!',
  err58: 'Invalid sequence number!',
  err59: 'Invalid transaction currency!',
  err101: 'Page request error - Missing required transaction parameter or an unacceptable value provided',
  err102: 'Transaction time expired',
  err103: 'Invalid transfer amount',
  err104: 'Transaction awaiting confirmation',
  err105: 'Transaction completed after the allowed time',
  err161:
    "Transaction request aborted by user - User canceled the payment process by selecting 'Back' on the payment method selection page",
  err162: "Transaction request aborted by user - User canceled the payment process by selecting 'Cancel' on the payment instructions page",
};
